spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: trackerfitness970@gmail.com
    password: iksn yuve kmnp ojsd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
